// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFE89cTLuJlNDazgE_OBWeJTmZhjyH2ho',
    appId: '1:74752992259:web:e2a5e9637b025169991a36',
    messagingSenderId: '74752992259',
    projectId: 'login-39a84',
    authDomain: 'login-39a84.firebaseapp.com',
    storageBucket: 'login-39a84.appspot.com',
    measurementId: 'G-SF8V68GBFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4Rvqke-XpwIVuwHVbc_7BzFfYuR3zIts',
    appId: '1:74752992259:android:fbe7c56337bc6778991a36',
    messagingSenderId: '74752992259',
    projectId: 'login-39a84',
    storageBucket: 'login-39a84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYGsFP3-ssGiUl-nkizrYph_doxjP9Fvw',
    appId: '1:74752992259:ios:02d00855b2a73206991a36',
    messagingSenderId: '74752992259',
    projectId: 'login-39a84',
    storageBucket: 'login-39a84.appspot.com',
    iosClientId: '74752992259-basgnlk8sohdh9ehtmktjioc52hkd20b.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
